"use client";

import { AnalysisResult } from "@/lib/types";

interface ReportDisplayProps {
  report: AnalysisResult;
  onRestart: () => void;
}

export default function ReportDisplay({ report, onRestart }: ReportDisplayProps) {
  const downloadReport = () => {
    const content = `
RESUME ANALYSIS REPORT
=======================

ATS Score: ${report.atsScore}/100

HARD SKILLS MATCH: ${report.hardSkillsMatch.percent}%
${report.hardSkillsMatch.present}/${report.hardSkillsMatch.total} skills present

Present Hard Skills:
${report.hardSkillsMatch.presentSkills.join(", ") || "None"}

Missing Hard Skills:
${report.hardSkillsMatch.missingSkills.slice(0, 10).join(", ") || "None"}

---

SOFT SKILLS MATCH: ${report.softSkillsMatch.percent}%
${report.softSkillsMatch.present}/${report.softSkillsMatch.total} skills present

Present Soft Skills:
${report.softSkillsMatch.presentSkills.join(", ") || "None"}

Missing Soft Skills:
${report.softSkillsMatch.missingSkills.slice(0, 10).join(", ") || "None"}

---

OVERVIEW:
${report.overview}

---

MISSING SECTIONS:
${report.missingSections.length > 0 ? report.missingSections.join(", ") : "All sections present"}

---

RECOMMENDATIONS:
${report.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join("\n")}

Generated by ResumeAnalyzer
    `;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `resume-analysis-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-8">
      {/* Overview Section */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h2 className="text-3xl font-bold text-gray-800 mb-6">Analysis Report</h2>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          {/* ATS Score */}
          <div className="bg-gradient-to-br from-yellow-50 to-yellow-100 p-6 rounded-lg">
            <p className="text-gray-600 text-sm font-semibold mb-4">
              ATS Match Score
            </p>
            <div className="flex items-center justify-center">
              <div
                className="relative w-32 h-32 rounded-full flex items-center justify-center text-4xl font-bold"
                style={{
                  background: `conic-gradient(#fbbf24 0deg, #fbbf24 ${
                    report.atsScore * 3.6
                  }deg, #e5e7eb ${report.atsScore * 3.6}deg, #e5e7eb 360deg)`,
                }}
              >
                <span className="absolute bg-white rounded-full w-24 h-24 flex items-center justify-center text-3xl font-bold text-yellow-500">
                  {report.atsScore}
                </span>
              </div>
            </div>
          </div>

          {/* Hard Skills */}
          <div className="bg-gradient-to-br from-blue-50 to-blue-100 p-6 rounded-lg">
            <p className="text-gray-600 text-sm font-semibold mb-2">
              Hard Skills Match
            </p>
            <p className="text-4xl font-bold text-blue-600 mb-2">
              {report.hardSkillsMatch.percent}%
            </p>
            <p className="text-sm text-gray-600">
              {report.hardSkillsMatch.present}/{report.hardSkillsMatch.total} present
            </p>
          </div>

          {/* Soft Skills */}
          <div className="bg-gradient-to-br from-purple-50 to-purple-100 p-6 rounded-lg">
            <p className="text-gray-600 text-sm font-semibold mb-2">
              Soft Skills Match
            </p>
            <p className="text-4xl font-bold text-purple-600 mb-2">
              {report.softSkillsMatch.percent}%
            </p>
            <p className="text-sm text-gray-600">
              {report.softSkillsMatch.present}/{report.softSkillsMatch.total} present
            </p>
          </div>

          {/* Missing Sections */}
          <div className="bg-gradient-to-br from-green-50 to-green-100 p-6 rounded-lg">
            <p className="text-gray-600 text-sm font-semibold mb-2">
              Missing Sections
            </p>
            <p className="text-4xl font-bold text-green-600 mb-2">
              {report.missingSections.length}
            </p>
            <p className="text-sm text-gray-600">to add</p>
          </div>
        </div>

        {/* Overview Text */}
        <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded">
          <p className="text-blue-900 font-semibold">📊 Overview</p>
          <p className="text-blue-700 text-sm mt-2">{report.overview}</p>
        </div>
      </div>

      {/* Skills Analysis */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6">Skills Analysis</h3>

        {/* Hard Skills */}
        <div className="mb-8">
          <h4 className="text-lg font-semibold text-gray-800 mb-4">
            Hard Skills ({report.hardSkillsMatch.percent}%)
          </h4>
          <div className="space-y-3">
            <div>
              <p className="text-sm font-semibold text-green-700 mb-2">Present:</p>
              <div className="flex flex-wrap gap-2">
                {report.hardSkillsMatch.presentSkills.length > 0 ? (
                  report.hardSkillsMatch.presentSkills.map((skill) => (
                    <span
                      key={skill}
                      className="inline-block bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium"
                    >
                      ✓ {skill}
                    </span>
                  ))
                ) : (
                  <p className="text-gray-500 text-sm">No matching skills found</p>
                )}
              </div>
            </div>

            {report.hardSkillsMatch.missingSkills.length > 0 && (
              <div>
                <p className="text-sm font-semibold text-red-700 mb-2">Missing:</p>
                <div className="flex flex-wrap gap-2">
                  {report.hardSkillsMatch.missingSkills.map((skill) => (
                    <span
                      key={skill}
                      className="inline-block bg-red-100 text-red-800 px-3 py-1 rounded-full text-sm font-medium"
                    >
                      ✗ {skill}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Soft Skills */}
        <div>
          <h4 className="text-lg font-semibold text-gray-800 mb-4">
            Soft Skills ({report.softSkillsMatch.percent}%)
          </h4>
          <div className="space-y-3">
            <div>
              <p className="text-sm font-semibold text-purple-700 mb-2">Present:</p>
              <div className="flex flex-wrap gap-2">
                {report.softSkillsMatch.presentSkills.length > 0 ? (
                  report.softSkillsMatch.presentSkills.map((skill) => (
                    <span
                      key={skill}
                      className="inline-block bg-purple-100 text-purple-800 px-3 py-1 rounded-full text-sm font-medium"
                    >
                      ✓ {skill}
                    </span>
                  ))
                ) : (
                  <p className="text-gray-500 text-sm">No matching soft skills</p>
                )}
              </div>
            </div>

            {report.softSkillsMatch.missingSkills.length > 0 && (
              <div>
                <p className="text-sm font-semibold text-red-700 mb-2">To Highlight:</p>
                <div className="flex flex-wrap gap-2">
                  {report.softSkillsMatch.missingSkills.map((skill) => (
                    <span
                      key={skill}
                      className="inline-block bg-red-100 text-red-800 px-3 py-1 rounded-full text-sm font-medium"
                    >
                      ✗ {skill}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Resume Sections */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6">Resume Sections</h3>
        <div className="space-y-3">
          {["Contact Information", "Professional Summary", "Work Experience", "Education", "Skills", "Certifications", "Projects"].map(
            (section) => {
              const isPresent = report.missingSections.every(
                (s) => s !== section
              );
              return (
                <div
                  key={section}
                  className="flex items-center justify-between p-4 border border-gray-200 rounded-lg"
                >
                  <span
                    className={`font-semibold ${
                      isPresent ? "text-green-600" : "text-red-600"
                    }`}
                  >
                    {isPresent ? "✓" : "✗"} {section}
                  </span>
                  {!isPresent && (
                    <span className="text-xs bg-red-100 text-red-700 px-2 py-1 rounded">
                      Missing
                    </span>
                  )}
                </div>
              );
            }
          )}
        </div>
      </div>

      {/* Recommendations */}
      <div className="bg-white rounded-lg shadow-lg p-8">
        <h3 className="text-2xl font-bold text-gray-800 mb-6">
          Recommendations
        </h3>
        <div className="space-y-3">
          {report.recommendations.map((rec, idx) => (
            <div
              key={idx}
              className="flex gap-4 p-4 bg-blue-50 border border-blue-200 rounded-lg"
            >
              <span className="flex-shrink-0 w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center text-sm font-semibold">
                {idx + 1}
              </span>
              <p className="text-gray-700">{rec}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 mb-8">
        <button
          onClick={downloadReport}
          className="flex-1 bg-green-500 hover:bg-green-600 text-white font-semibold py-3 rounded-lg transition flex items-center justify-center gap-2"
        >
          📥 Download Report
        </button>
        <button
          onClick={onRestart}
          className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-3 rounded-lg transition"
        >
          Start Over
        </button>
      </div>
    </div>
  );
}